# Site settings
name: Cedric Amaya
title: Cedric Amaya | Software Developer
description: JavaScript aficionado passionate about creating exciting and memorable experiences using web technologies.
url: https://cedric.tech/
baseurl: ""
email: amaya.cedric@gmail.com
cover: https://cedric.tech/img/og.png
logo: https://cedric.tech/img/emojis/technologist.png
resume: https://cedric.tech/resume2018.pdf
social:
  - title: email
    url: mailto:amaya.cedric@gmail.com
  - title: blog
    url: https://cedric.tech/blog
  - title: twitter
    url: https://twitter.com/CedricAmaya
  - title: github
    url: https://github.com/cedricium
  - title: linkedin
    url: https://www.linkedin.com/in/cedricamaya

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins:
  - jekyll-minifier
  - jekyll-sitemap
